name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [24.x] # valid Node LTS

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }} # define in GitHub repo secrets

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npm run build --if-present
    - run: |
        echo "module.exports = { url: '${MONGODB_URL}' };" > app/config/db.config.js
